CREATE TABLE tsk_cards (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_cards_nn_tenant_id NOT NULL,
    client_id                       NUMBER(10,0)          CONSTRAINT tsk_cards_nn_client_id NOT NULL,
    project_id                      NUMBER(10,0)          CONSTRAINT tsk_cards_nn_project_id NOT NULL,
    card_id                         NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_cards_nn_card_id NOT NULL,
    card_number                     VARCHAR2(16),
    card_name                       VARCHAR2(128)         CONSTRAINT tsk_cards_nn_card_name NOT NULL,
    card_desc                       VARCHAR2(4000),
    board_id                        NUMBER(10,0)          CONSTRAINT tsk_cards_nn_board_id NOT NULL,
    milestone_id                    NUMBER(10,0)          CONSTRAINT tsk_cards_nn_milestone_id NOT NULL,
    status_id                       NUMBER(10,0)          CONSTRAINT tsk_cards_nn_status_id NOT NULL,
    category_id                     NUMBER(10,0),
    owner_id                        VARCHAR2(128),
    deadline_at                     DATE,
    tags                            VARCHAR2(256),
    order#                          NUMBER(10,0),
    created_by                      VARCHAR2(128)         CONSTRAINT tsk_cards_nn_created_by NOT NULL,
    created_at                      DATE                  CONSTRAINT tsk_cards_nn_created_at NOT NULL,
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_cards_pk
        PRIMARY KEY (
            tenant_id,
            client_id,
            project_id,
            card_id
        ),
    --
    CONSTRAINT tsk_cards_uq
        UNIQUE (
            tenant_id,
            card_id
        ),
    --
    CONSTRAINT tsk_cards_fk_milestones
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id,
            milestone_id
        )
        REFERENCES tsk_milestones (
            tenant_id,
            client_id,
            project_id,
            milestone_id
        ),
    --
    CONSTRAINT tsk_cards_fk_statuses
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id,
            status_id
        )
        REFERENCES tsk_statuses (
            tenant_id,
            client_id,
            project_id,
            status_id
        ),
    --
    CONSTRAINT tsk_cards_fk_categories
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id,
            category_id
        )
        REFERENCES tsk_categories (
            tenant_id,
            client_id,
            project_id,
            category_id
        )
);
--
COMMENT ON TABLE tsk_cards IS '';
--
COMMENT ON COLUMN tsk_cards.tenant_id       IS '';
COMMENT ON COLUMN tsk_cards.client_id       IS '';
COMMENT ON COLUMN tsk_cards.project_id      IS '';
COMMENT ON COLUMN tsk_cards.card_id         IS '';
COMMENT ON COLUMN tsk_cards.card_number     IS '';
COMMENT ON COLUMN tsk_cards.card_name       IS '';
COMMENT ON COLUMN tsk_cards.card_desc       IS '';
COMMENT ON COLUMN tsk_cards.board_id        IS '';
COMMENT ON COLUMN tsk_cards.milestone_id    IS '';
COMMENT ON COLUMN tsk_cards.status_id       IS '';
COMMENT ON COLUMN tsk_cards.category_id     IS '';
COMMENT ON COLUMN tsk_cards.owner_id        IS '';
COMMENT ON COLUMN tsk_cards.deadline_at     IS '';
COMMENT ON COLUMN tsk_cards.tags            IS '';
COMMENT ON COLUMN tsk_cards.order#          IS '';

