CREATE TABLE tsk_categories (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_categories_nn_tenant_id NOT NULL,
    client_id                       NUMBER(10,0)          CONSTRAINT tsk_categories_nn_client_id NOT NULL,
    project_id                      NUMBER(10,0)          CONSTRAINT tsk_categories_nn_project_id NOT NULL,
    category_id                     NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_categories_nn_category_id NOT NULL,
    category_name                   VARCHAR2(64)          CONSTRAINT tsk_categories_nn_category_name NOT NULL,
    category_group                  VARCHAR2(64),
    color_bg                        VARCHAR2(8),
    color_fg                        VARCHAR2(8),
    is_default                      CHAR(1),
    is_active                       CHAR(1),
    order#                          NUMBER(4,0),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_categories_ch_is_active
        CHECK (
            is_active = 'Y' OR is_active IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_categories_ch_is_default
        CHECK (
            is_default = 'Y' OR is_default IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_categories_pk
        PRIMARY KEY (
            tenant_id,
            client_id,
            project_id,
            category_id
        ),
    --
    CONSTRAINT tsk_categories_fk_projects
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id
        )
        REFERENCES tsk_projects (
            tenant_id,
            client_id,
            project_id
        )
);
--
COMMENT ON TABLE tsk_categories IS '';
--
COMMENT ON COLUMN tsk_categories.tenant_id          IS '';
COMMENT ON COLUMN tsk_categories.client_id          IS '';
COMMENT ON COLUMN tsk_categories.project_id         IS '';
COMMENT ON COLUMN tsk_categories.category_id        IS '';
COMMENT ON COLUMN tsk_categories.category_name      IS '';
COMMENT ON COLUMN tsk_categories.category_group     IS '';
COMMENT ON COLUMN tsk_categories.color_bg           IS '';
COMMENT ON COLUMN tsk_categories.color_fg           IS '';
COMMENT ON COLUMN tsk_categories.is_default         IS '';
COMMENT ON COLUMN tsk_categories.is_active          IS '';
COMMENT ON COLUMN tsk_categories.order#             IS '';

