CREATE TABLE tsk_milestones (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_milestones_tenant_nn NOT NULL,
    client_id                       NUMBER(10,0)          CONSTRAINT tsk_milestones_client_nn NOT NULL,
    project_id                      NUMBER(10,0)          CONSTRAINT tsk_milestones_project_nn NOT NULL,
    milestone_id                    NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_milestones_id_nn NOT NULL,
    milestone_name                  VARCHAR2(64)          CONSTRAINT tsk_milestones_name_nn NOT NULL,
    is_active                       CHAR(1),
    order#                          NUMBER(4,0),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_milestones_ch
        CHECK (
            is_active = 'Y' OR is_active IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_milestones_pk
        PRIMARY KEY (
            tenant_id,
            client_id,
            project_id,
            milestone_id
        ),
    --
    CONSTRAINT tsk_milestones_project_fk
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id
        )
        REFERENCES tsk_projects (
            tenant_id,
            client_id,
            project_id
        )
);
--
COMMENT ON TABLE tsk_milestones IS '';
--
COMMENT ON COLUMN tsk_milestones.tenant_id          IS '';
COMMENT ON COLUMN tsk_milestones.client_id          IS '';
COMMENT ON COLUMN tsk_milestones.project_id         IS '';
COMMENT ON COLUMN tsk_milestones.milestone_id       IS '';
COMMENT ON COLUMN tsk_milestones.milestone_name     IS '';
COMMENT ON COLUMN tsk_milestones.is_active          IS '';
COMMENT ON COLUMN tsk_milestones.order#             IS '';

