CREATE TABLE tsk_statuses (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_statuses_nn_tenant_id NOT NULL,
    client_id                       NUMBER(10,0)          CONSTRAINT tsk_statuses_nn_client_id NOT NULL,
    project_id                      NUMBER(10,0)          CONSTRAINT tsk_statuses_nn_project_id NOT NULL,
    status_id                       NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_statuses_nn_status_id NOT NULL,
    status_name                     VARCHAR2(64)          CONSTRAINT tsk_statuses_nn_status_name NOT NULL,
    status_group                    VARCHAR2(64),
    col_order#                      NUMBER(4,0),
    row_order#                      NUMBER(4,0),
    is_colored                      CHAR(1),
    is_badge                        CHAR(1),
    is_default                      CHAR(1),
    is_active                       CHAR(1),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_statuses_ch_is_active
        CHECK (
            is_active = 'Y' OR is_active IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_statuses_ch_is_default
        CHECK (
            is_default = 'Y' OR is_default IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_statuses_ch_is_colored
        CHECK (
            is_colored = 'Y' OR is_colored IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_statuses_ch_is_badge
        CHECK (
            is_badge='Y' OR is_badge IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_statuses_pk
        PRIMARY KEY (
            tenant_id,
            client_id,
            project_id,
            status_id
        ),
    --
    CONSTRAINT tsk_statuses_fk_projects
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id
        )
        REFERENCES tsk_projects (
            tenant_id,
            client_id,
            project_id
        )
);
--
COMMENT ON TABLE tsk_statuses IS '';
--
COMMENT ON COLUMN tsk_statuses.tenant_id        IS '';
COMMENT ON COLUMN tsk_statuses.client_id        IS '';
COMMENT ON COLUMN tsk_statuses.project_id       IS '';
COMMENT ON COLUMN tsk_statuses.status_id        IS '';
COMMENT ON COLUMN tsk_statuses.status_name      IS '';
COMMENT ON COLUMN tsk_statuses.status_group     IS '';
COMMENT ON COLUMN tsk_statuses.col_order#       IS '';
COMMENT ON COLUMN tsk_statuses.row_order#       IS '';
COMMENT ON COLUMN tsk_statuses.is_colored       IS '';
COMMENT ON COLUMN tsk_statuses.is_badge         IS '';
COMMENT ON COLUMN tsk_statuses.is_default       IS '';
COMMENT ON COLUMN tsk_statuses.is_active        IS '';

