CREATE TABLE tsk_card_files (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_card_files_tenant_nn NOT NULL,
    card_id                         NUMBER(10,0)          CONSTRAINT tsk_card_files_card_nn NOT NULL,
    file_id                         NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_card_files_id_nn NOT NULL,
    file_name                       VARCHAR2(256)         CONSTRAINT tsk_card_files_name_nn NOT NULL,
    file_mime                       VARCHAR2(256)         CONSTRAINT tsk_card_files_mime_nn NOT NULL,
    file_size                       NUMBER                CONSTRAINT tsk_card_files_len_nn NOT NULL,
    file_payload                    BLOB,
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_card_files_pk
        PRIMARY KEY (
            tenant_id,
            card_id,
            file_id
        ),
    --
    CONSTRAINT tsk_card_files_uq
        UNIQUE (
            tenant_id,
            file_id
        ),
    --
    CONSTRAINT tsk_card_files_name_uq
        UNIQUE (
            tenant_id,
            card_id,
            file_name
        ),
    --
    CONSTRAINT tsk_card_files_card_fk
        FOREIGN KEY (
            tenant_id,
            card_id
        )
        REFERENCES tsk_cards (
            tenant_id,
            card_id
        )
);
--
COMMENT ON TABLE tsk_card_files IS '';
--
COMMENT ON COLUMN tsk_card_files.tenant_id      IS '';
COMMENT ON COLUMN tsk_card_files.card_id        IS '';
COMMENT ON COLUMN tsk_card_files.file_id        IS '';
COMMENT ON COLUMN tsk_card_files.file_name      IS '';
COMMENT ON COLUMN tsk_card_files.file_mime      IS '';
COMMENT ON COLUMN tsk_card_files.file_size      IS '';
COMMENT ON COLUMN tsk_card_files.file_payload   IS '';

