CREATE TABLE tsk_boards (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_boards_tenant_nn NOT NULL,
    client_id                       NUMBER(10,0)          CONSTRAINT tsk_boards_client_nn NOT NULL,
    project_id                      NUMBER(10,0)          CONSTRAINT tsk_boards_project_nn NOT NULL,
    board_id                        NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_boards_board_nn NOT NULL,
    board_name                      VARCHAR2(64)          CONSTRAINT tsk_boards_name_nn NOT NULL,
    sequence_id                     VARCHAR2(32),
    is_simple                       CHAR(1),
    is_default                      CHAR(1),
    is_active                       CHAR(1),
    order#                          NUMBER(4,0),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_boards_ch
        CHECK (
            is_active = 'Y' OR is_active IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_boards_default_ch
        CHECK (
            is_default = 'Y' OR is_default IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_boards_simple_ch
        CHECK (
            is_simple = 'Y' OR is_simple IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_boards_pk
        PRIMARY KEY (
            tenant_id,
            client_id,
            project_id,
            board_id
        ),
    --
    CONSTRAINT tsk_boards_uq
        UNIQUE (
            tenant_id,
            board_id
        ),
    --
    CONSTRAINT tsk_boards_project_fk
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id
        )
        REFERENCES tsk_projects (
            tenant_id,
            client_id,
            project_id
        ),
    --
    CONSTRAINT tsk_boards_sequence_fk
        FOREIGN KEY (
            tenant_id,
            client_id,
            project_id,
            sequence_id
        )
        REFERENCES tsk_sequences (
            tenant_id,
            client_id,
            project_id,
            sequence_id
        )
);
--
COMMENT ON TABLE tsk_boards IS '';
--
COMMENT ON COLUMN tsk_boards.tenant_id      IS '';
COMMENT ON COLUMN tsk_boards.client_id      IS '';
COMMENT ON COLUMN tsk_boards.project_id     IS '';
COMMENT ON COLUMN tsk_boards.board_id       IS '';
COMMENT ON COLUMN tsk_boards.board_name     IS '';
COMMENT ON COLUMN tsk_boards.sequence_id    IS '';
COMMENT ON COLUMN tsk_boards.is_simple      IS '';
COMMENT ON COLUMN tsk_boards.is_default     IS '';
COMMENT ON COLUMN tsk_boards.is_active      IS '';
COMMENT ON COLUMN tsk_boards.order#         IS '';

