CREATE TABLE tsk_card_checklist (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_card_checklist_tenant_nn NOT NULL,
    card_id                         NUMBER(10,0)          CONSTRAINT tsk_card_checklist_card_nn NOT NULL,
    checklist_id                    NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_card_checklist_checklist_nn NOT NULL,
    checklist_item                  VARCHAR2(256)         CONSTRAINT tsk_card_checklist_item_nn NOT NULL,
    checklist_done                  CHAR(1),
    checklist_level                 NUMBER(4,0),
    order#                          VARCHAR2(32),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_card_checklist_done_ch
        CHECK (
            checklist_done = 'Y' OR checklist_done IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_card_checklist_pk
        PRIMARY KEY (
            tenant_id,
            checklist_id
        ),
    --
    CONSTRAINT tsk_card_checklist_card_fk
        FOREIGN KEY (
            tenant_id,
            card_id
        )
        REFERENCES tsk_cards (
            tenant_id,
            card_id
        )
);
--
COMMENT ON TABLE tsk_card_checklist IS '';
--
COMMENT ON COLUMN tsk_card_checklist.tenant_id          IS '';
COMMENT ON COLUMN tsk_card_checklist.card_id            IS '';
COMMENT ON COLUMN tsk_card_checklist.checklist_id       IS '';
COMMENT ON COLUMN tsk_card_checklist.checklist_item     IS '';
COMMENT ON COLUMN tsk_card_checklist.checklist_done     IS '';
COMMENT ON COLUMN tsk_card_checklist.checklist_level    IS '';
COMMENT ON COLUMN tsk_card_checklist.order#             IS '';

