CREATE TABLE tsk_projects (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_projects_tenant_nn NOT NULL,
    client_id                       NUMBER(10,0)          CONSTRAINT tsk_projects_client_nn NOT NULL,
    project_id                      NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_projects_project_nn NOT NULL,
    project_name                    VARCHAR2(64)          CONSTRAINT tsk_projects_name_nn NOT NULL,
    is_active                       CHAR(1),
    is_default                      CHAR(1),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_projects_ch
        CHECK (
            is_active = 'Y' OR is_active IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_projects_default_ch
        CHECK (
            is_default = 'Y' OR is_default IS NULL
        ) ENABLE,
    --
    CONSTRAINT tsk_projects_pk
        PRIMARY KEY (
            tenant_id,
            client_id,
            project_id
        ),
    --
    CONSTRAINT tsk_projects_client_fk
        FOREIGN KEY (
            tenant_id,
            client_id
        )
        REFERENCES tsk_clients (
            tenant_id,
            client_id
        )
);
--
COMMENT ON TABLE tsk_projects IS '';
--
COMMENT ON COLUMN tsk_projects.tenant_id        IS '';
COMMENT ON COLUMN tsk_projects.client_id        IS '';
COMMENT ON COLUMN tsk_projects.project_id       IS '';
COMMENT ON COLUMN tsk_projects.project_name     IS '';
COMMENT ON COLUMN tsk_projects.is_active        IS '';
COMMENT ON COLUMN tsk_projects.is_default       IS '';

