CREATE TABLE tsk_repo_endpoints (
    tenant_id                       VARCHAR2(64)          CONSTRAINT tsk_repo_endpoints_tenant_nn NOT NULL,
    repo_id                         NUMBER(10,0)          CONSTRAINT tsk_repo_endpoint_repo_nn NOT NULL,
    endpoint_id                     NUMBER(10,0)          GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1000 CONSTRAINT tsk_repo_endpoint_id_nn NOT NULL,
    endpoint_url                    VARCHAR2(256),
    endpoint_body                   VARCHAR2(2000),
    endpoint_method                 VARCHAR2(8),
    updated_by                      VARCHAR2(128),
    updated_at                      DATE,
    --
    CONSTRAINT tsk_repo_endpoint_pk
        PRIMARY KEY (
            tenant_id,
            repo_id,
            endpoint_id
        ),
    --
    CONSTRAINT tsk_repo_endpoint_repos_fk
        FOREIGN KEY (
            tenant_id,
            repo_id
        )
        REFERENCES tsk_repos (
            tenant_id,
            repo_id
        )
);
--
COMMENT ON TABLE tsk_repo_endpoints IS '';
--
COMMENT ON COLUMN tsk_repo_endpoints.tenant_id          IS '';
COMMENT ON COLUMN tsk_repo_endpoints.repo_id            IS '';
COMMENT ON COLUMN tsk_repo_endpoints.endpoint_id        IS '';
COMMENT ON COLUMN tsk_repo_endpoints.endpoint_url       IS '';
COMMENT ON COLUMN tsk_repo_endpoints.endpoint_body      IS '';
COMMENT ON COLUMN tsk_repo_endpoints.endpoint_method    IS '';

