---
# ====== Application: Card Crunchers =========================
id: 710
identification: 
  name: Card Crunchers
  alias: CARDS
  version: 2023-09-20
  application-group: LAUNCHPAD # 14521045818542929

row-search: 
  tokenize: true

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: core.handle_apex_error

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 / 22.1 / 22.2
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: OPEN_DOOR (TESTING ONLY) # 28681044215599643

authorization: 
  source-for-role-or-group-schemes: Custom Code

session-management: 
  rejoin-sessions: Disabled
  maximum-session-length: 32400
  session-timeout-url: '/ords/f?p=800:9999:0::::P9999_ERROR:SESSION_TIMEOUT'
  maximum-session-idle-time: 5400
  session-idle-timeout-url: '/ords/f?p=800:9999:0::::P9999_ERROR:SESSION_TIMEOUT'
  session-timeout-warning: 90

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: APPS

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: false

application-format-masks: 
  date: '&FORMAT_DATE.'
  date-time: '&FORMAT_DATE_TIME.'
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APP_NAME.'

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:HOME:&APP_SESSION.::&DEBUG.:::'
    page: HOME

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Top Navigation Menu # 34014612441153815
  template-options: 
  - '#DEFAULT#'
  - js-tabLike
  list-position: Top

navigation-bar: 
  implementation: List
  list: NAVIGATION # 28802196659285496
  list-template: Navigation Q23 # 31684266225644159
  template-options: 
  - '#DEFAULT#'

javascript: 
  file-urls: 
  - '#WORKSPACE_FILES#master_app#MIN#.js?version=#APP_VERSION#'
  - '#APP_FILES#tsk_app#MIN#.js?version=#APP_VERSION#'
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#WORKSPACE_FILES#master_fonts#MIN#.css?version=#APP_VERSION#'
  - '#WORKSPACE_FILES#master_menu_top#MIN#.css?version=#APP_VERSION#'
  - '#WORKSPACE_FILES#master_app#MIN#.css?version=#APP_VERSION#'
  - '#APP_FILES#tsk_app#MIN#.css?version=#APP_VERSION#'

attributes: 
  theme: Universal Theme # 800
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Card Crunchers

- # ====== Substitution: APP_DESC ==============================
  id: 2
  identification: 
    name: APP_DESC

  value: 
    static-value: Simple tasks/cards management on kanban style board with checklists/acceptance criteria and more...

- # ====== Substitution: APP_PREFIX ============================
  id: 3
  identification: 
    name: APP_PREFIX

  value: 
    static-value: TSK_

component-settings: 
- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 1388154471820069
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 39913487784091

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 97829385400921744
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 97829679008921746
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 97829963791921746
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 97830601760921746
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  settings: 
    attribute-1: Y

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 97830838325921746
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 97831183395921747
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_IR ========================
  id: 97831504065921747
  identification: 
    name: NATIVE_IR
    type: Region

  settings: 
    attribute-1: IG

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 97831763795921747
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 1

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 97832030356921747
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 1

